### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by Skruf90** [G-Ray/candyflix#1]
Hi there. 

I've followed your guide as good as I could. I installed peerflix. I then moved frontend and unpacked it into my server /www folder. 

I then did a npm install in app folder generating node_modules. The site now loads ( mainly because of the html files. ). 

But when I do node Candyflix.js nothing really happens, I guess its because I haven't done this part:
"Set a proxypass to redirect from /socket.io/ to http://localhost:3000". How do I do that?

**Comment by G-Ray** [comment]
Hi !

I added a proxy example for nginx. Tell me if you can get it working ;)

**Comment by Skruf90** [comment]
Ok. I know managed to make the server running. Thank you for adding the nginx example. 
I do get some wierd errors though when browsing, like not all contect comes up, and playback is kind off messy. I browse to http://localhost, as localhost:3000 gives me blank page. Though the terminal is recognizing me as prospector. Is that an issue? Also will you implant the 5.0 design of PCT?

http://dl.dropbox.com/u/2026084/Selection_015.png
http://dl.dropbox.com/u/2026084/Selection_016.png
http://dl.dropbox.com/u/2026084/Selection_017.png
http://dl.dropbox.com/u/2026084/Selection_018.png
http://dl.dropbox.com/u/2026084/Selection_019.png

**Comment by G-Ray** [comment]
Only mp4 files can be played through the browser. That's why you have this message about VLC, because you can still play the video with it.
If you've got the message "The video could not be loaded...", that's because the server on which candyflix is running was not able to start the video stream early enough. That may be due to your server connection.
Candyflix is not able to determine when a video stream is ready to be played ATM. By default, the video starts to be played 6 second after the play button has been pushed. I will increase this ASAP, and this would hopefully solve your movie playback issues :+1: 
See https://github.com/G-Ray/candyflix/blob/master/frontend/js/ui.js#L324 and similar lines.

I may implement 5.0 design, but I don't think this would be an easy task. I'm a bit busy these days.

**Comment by Skruf90** [comment]
Awesome :). If you have the files for the design I would be happy to help out with implenting the 5.0 design.

**Comment by G-Ray** [comment]
Take a look at http://popcorn-time.se/source.html, you can download the sources for the desktop app.

Contributions would be welcome :)

**Comment by Skruf90** [comment]
Do you have any details on how to build the T4P sources? Kind of different files than PCT.io source.

**Comment by G-Ray** [comment]
I took a look on the sources, but the readme is not really helpful...
However the interface is built with Qt I think

**Comment by Skruf90** [comment]
Aiight mate. I have found the UI design. Its not on app.popcorn-time.se as before its now on http://ui.popcorn-time.se/ . I will start exploring it. 

//Update 1: 

I've managed to implant the new design from the site above. It loads all the movies/tv-shows but it wount play. I'm thinking its a problem with the app.js as the console is referring to: 

" Uncaught ReferenceError: hostApp is not defined"
"torrent:{

```
    current_torrent_id: '',

    get: function(session){
        hostApp.getTorrent(session);
    },"
```

**Comment by G-Ray** [comment]
Amazing !!! Good job :) !
Don't hesitate to download the entire website with wget ;)

I can give you some help if you need, I will create a new develop branch in
candyflix, in order to keep master functional

**Comment by G-Ray** [comment]
Don't hesitate to download the entire website with wget ;)

I can give you some help if you need, I will create a new develop branch in
candyflix, in order to keep master functional

**Comment by Skruf90** [comment]
Awesome. Create a developer branch so we can make this work with 5.0 design :)

Edit: I am ready to start adding to develop branch. Have you made it :)?

**Comment by Skruf90** [comment]
Hey mate :). I see that you have created a develop branch. Have you managed to make it work :) ?

**Comment by G-Ray** [comment]
Hi,

I haven't made any progress at the moment. Sorry I am a bit busy these times...

**Comment by Skruf90** [comment]
I see.

**Comment by Skruf90** [comment]
No problem :) I will try to contribute myself If you dont beat me :dancers:

**Comment by G-Ray** [comment]
Yeah, please do :)

**Comment by nilparra** [comment]
Salut G-Ray

J'utilisais avant yify-pop et je suis tombé sur ton post sur le github de yify pour donner un peu d'aide au projet. Du coup, curieux je suis aller voir candyflix et je dois te dire que ton travail est génial. 

Je viens de l'installer et j'ai définitivement mit de coté yify pop.

C'est du très bon boulot. Félicitation !

Je suis ton github attentivement pour voir les évolutions que tu vas faire. Tu as des features dans ton sac ou tu as mis le projet de coté ?

Amicalement,

Nil

**Comment by G-Ray** [comment]
Salut !

Merci pour ce compliment ^^. En réalité je n'ai réalisé que la partie
serveur, le frontend provient de time4popcorn (le fork qui n'a pas bonne
réputation il paraît...), auquel j'ai apporté quelques modifications.

En ce moment le projet est en pause, mais je compte bientôt remplacer
l'interface par celle de la nouvelle verison de time4popcorn dispo ici :
http://ui.popcorn-time.se

N'hésite pas à y contribuer ;)

2015-05-19 20:31 GMT+02:00 nilparra notifications@github.com:

**Comment by nilparra** [comment]
La partie serveur c'est la plus importante :) Ne sois pas humble comme ça :)

Je vais essayer de participer un peu, je n'ai jamais fait de nodejs mais je suis très bon en PHP, JS, CSS.

Quelques questions :
- Se serait pas mal de voir les torrents en cours comme sur Yify-pop et pouvoir les stopper quand on a fini. Mine de rien ça sert pas mal de pouvoir les arreter car si tu lances un film et que finalement tu ne le regarde pas et bien il continue de le dl et occupe ta bande passante.
- Tu utilises le tracker fr cpasbien si j'ai bien compris. Se serait pas mal d'afficher les films et series qui sont en FR ou VOST dans la fiche ( sauf si c'est présent mais que j'ai pas bien vu).
- Pourrais tu me faire une présentation par skype ? vite fait sur le projet pour que je puisse rapidement y contribuer. dossier etc..

**Comment by G-Ray** [comment]
Les processus peerflix sont terminés dès qu'il n'y a plus aucun spectateur. Tu peux voir les films en cours avec le nombre de spectateurs dans la console du serveur. Le scraper cpasbien est pour l'instant sur une version perso, je l'integrerai à candyflix.

Contacte moi par mail pour le reste :)

**Comment by nilparra** [comment]
Ok merci pour les infos. tant mieux pour les processus peerflix :)

Comment j'obtiens ton adresse email ? lol

**Comment by G-Ray** [comment]
sur mon profil github

**Comment by mistertest** [comment]
Bonjour à vous, c'est clair que G-Ray ta modestie est tout à ton honneur, c'est du taf excellent . j’essaierais d'apporter quelques trucs également et commencer par remonter certaines choses. Je suis curieux de voir la suite dont la fameuse intégration du fr.

**Comment by Yopfa** [comment]
Beau boulot, également très curieux de voir l'intégration du Fr, par contre je les installer, mais je trouve que ça rame un peu pour l'affichage des films / séries. Peut être me suis louper.. pourtant la machine tourne à 2%cpu et 1% ram. Bref à voir..

**Comment by G-Ray** [comment]
Les affiches sont fetchées depuis le navigateur du client, puis sont mis en cache pour que ça aille plus vite les fois d'après

**Comment by Yopfa** [comment]
Effectivement ;).Merci.
Impeccable. Hâte de voir l'intégration de Cpasbien.

**Comment by mistertest** [comment]
Hello, je me suis mis à apprendre à scrapper avec node js. C'est très intéressant et forcément j'ai testé avec cpas bueno. Donc après plusieurs technos dont les scrappeur en ligne (Kimono io ) j'utilise le module npm  claw c'est rapide et très clair. Il sauvegarde les json dans des dossiers de destination, il y a aussi le csv en sortie.  Il est également utilisable en mode terminal ce qui est pratique pour les tests lives et ça ouvre la possibilité de lancer des commandes cron régulieres sur le serveur.  Il permet de scraper plusieurs pages à la foi et de sortir autant de json, ou alors de tout unifier sur le même json.
Il est très peu connu, le code est compréhensible par le débutant node que je suis c'est ce qui m'a plu.Je vous le conseille.

**Comment by mistertest** [comment]
En terminal tout est ok par contre je ne comprends pas comment l'intégerer en tant que module avec yify-pop. je l'ai installé mais maintenant qu'est ce que je dois faire ?? Je voudrais faire un clic function qui lance le scrapping à partir de index.html.ejs mais je vois pas comment procéder. Si vous pouvez m'aider.

**Comment by mistertest** [comment]
J'ai fait les json de deux grandes categories : action et comédie

**Comment by mistertest** [comment]
Salut j'ai réusit à tout passer cpasb en json tout le catalogue, je me suis fait ma propre interface catalogue en js, parceque candyflix et yify-pop sont dédiés à yify et j'ai du mal à comprendre comment je pourais les relier sans me casser la tête des mois sur le code.

**Comment by mistertest** [comment]
![capxtrezer](https://cloud.githubusercontent.com/assets/12024566/7896885/7908faf0-06c8-11e5-9dc5-d85b42859be0.png)
Voià une capture de mon interface, ça ressemble à la new popcorn pour candyflx. Par contre les images issus de cpasbien sont vraiment naz en terme de qualité, comment je pourais faire sans trop me casser la tête pour en avoir de meilleure en résolution ? J'ai vue que pour candyflix c'est relié à tmdb.

**Comment by Yopfa** [comment]
mistertest pas mal beau boulot, le top serait de l'integrer dans candyflix. à voir.

**Comment by mistertest** [comment]
Merci yopfa, oui pour le scrapping et la récupe des données c'est Ok , par contre je réfléchis à une mise à jour des données de façon automatique : c'est à dire que quand des nouvelles videos apparaissent q'elles soient automatiquement listées sans la moindre intervention des fichiers json manuellement. Et c'est assez balaise mais faisable par des commandes crons qui lancerait un scrapping et sauvegarderait le json. L'autre soucis c'est que je dois éviter toutes intervention manuelles or là je suis obligé de modifier les json manuellement ( changement de lien images , torrents etc..). Bref il faut tout automatiser sans api. Une foi que ça sera bon avec les bons outils et la bonne méthode on y verra plus clair. Mais pour ça je dois coder sur ma propre interface par indépendance je peux coder ce que je veux, sur candyflix tout le code est relié à l'api yfi les titres sont en anglais etc donc je serais tres limité, par contre je partage mes résultats avec l'équipe ici si ils veulent faire des tests.

**Comment by G-Ray** [comment]
J'aurais le temps de m'occuper du scraper demain soir. Il met à jour le contenu automatiquement à chaque rafraîchissement de page

**Comment by mistertest** [comment]
Cool G-ray, je n'ai plus accès à ton code du scrapper cpb pour essayer de comprendre comment tu procèdes, peux tu me redonner le lien stp (en mp si ça te dérange ici) ? Ma solution  est pas trop mal , il y a juste à automatiser, j'apprends beaucoup sur le scrapping avec tout ça. Mon objectif c'est d'avoir un outil puissant de stream, ergonomique et surtout rapide. Je trouve popcorn tres rapide sur Pc/linux/mac mais très très lent sur android box. Donc j'ai testé la nouvelle interface que tu mets en place de candy sur ma box android sur une grd tv et la navigation n'est pas au point sur ce périphérique et ses navigateurs. Attention il y aucun soucis sur PC mais sur les box android pour le moment la navigation est très difficile, il y a tellement de subtilité visuelle avec jquery...
Je ne sais pas si c'est la même chose sur Android tablette mais je pense que oui également.

**Comment by mistertest** [comment]
Salut, j'ai réussi à automatiser les  modification des Json directement par Javascript et Jquery pour la mise en forme (changement de chemins href , extension de fichier etc). Pour  l'actualisation des contenus j'utilise les commandes linux et cron ainsi que pour le "merge" des fichiers json. Un cron par jour sera lancé je pourrais changé. J'aurais voulut un rafraîchissement à la volée mais je manque encore de pratique donc pour l'instant c'est un scrapper serveur. J'ai recherché ce lien que tu m'avais donné pour étudier ton code mais il est mort.

**Comment by mistertest** [comment]
J'ai quasiment terminé mon projet , il me manque quelques détails. Donc j'ai mis en place ce que j'avais imaginé avec les cron jobs et mes listes de contenus se mettent à jour automatiquement toutes les nuits avec des opérations d’assemblage sur les json. Je n'ai plus à faire aucune manipes , le top de la fainéantise, vive cron! Et toi  tu as pu avancer sur ton scrapping ?

**Comment by mistertest** [comment]
Salut, j'ai terminé mon projet depuis quelques semaines. J'ai pu scraper comme je voulais et j'ai une actualisation des contenus automatiquement tout les soirs. Mon interface  tourne avec un système de template en JS. Si tu as des questions sur ma méthode de scrapping n'hésites pas.
Bon courage pour la suite.

**Comment by Pafzedog** [comment]
Salut Mistertest, 

Et si tu mettais ton projet en ligne qu'on puisse le tester ;)

**Comment by hostile123** [comment]
Dead?

**Comment by mistertest** [comment]
Bonjour Pafzedog, mon projet n'a pas pour but d'être partagé sur un serveur public,je l'ai conçu pour être strictement privé et familial. Je ne divulguerai jamais l'adresse, par contre je pourrais faire un doublon de quelques pages sur un serveur public juste pour aider au dev , c'est à voir.

**Comment by G-Ray** [comment]
@mistertest Tu peux toujours mettre tout le code sur un repo Github, ou en forkant le dépot de candyflix ;)

**Comment by Pafzedog** [comment]
@mistertest je proposais plutôt que tu partage ton code comme le signale @g-ray, c'est un peu le principe de github ;)

**Comment by mistertest** [comment]
Ok je créerais un repo dédié prochainement (pas de fork parcequ'il n'y a aucune ligne de code issue de candyflix).

**Comment by Pafzedog** [comment]
Et bien ça c'est une bonne nouvelle, hâte de tester :)
