### ISSUE TITLE
Ubuntu Installation

### ISSUE THREAD

**Issue by cyber-cliff** [G-Ray/candyflix#10]
Hi,

Can anyone tell me step by step on how to setup this on ubuntu machine? Since i am really a beginner in linux. I just want to try this script.

Thanks,

**Comment by cyber-cliff** [comment]
Please guys i need assistance, i want to try this script.

**Comment by G-Ray** [comment]
Please follow the instructions found in the REAME, and tell me where you encounter any difficulty
