### ISSUE TITLE
can't run 'node candyflix.js'

### ISSUE THREAD

**Issue by b-corentin** [G-Ray/candyflix#12]
Hello,
I install nginx. Next, I install candyflix on 'var/www'. 
But when I run the last cmd 'node candyflix.js', nothing happening. I try to add proxypass on config.d/site_available/default... But It's the first time I use NGinx. So I don't know how it work.

Can I have a detail  to create virtualhost and proxy ?

Thanks !

**Comment by Pafzedog** [comment]
nothing will happen until you will open your web browser on your nginx site, it's a web app ;)

**Comment by G-Ray** [comment]
From now, you just have to run `npm run`. It's easier ;)
