### ISSUE TITLE
FLASH: srcnotfound

### ISSUE THREAD

**Issue by firesalp** [G-Ray/candyflix#13]
Hi,
I just tested candyflix, everything wasfine during installing, but when I'm trying to play any vid, FF tells me that "FLASH: srcnotfound", and Chrome says "The video could not be loaded, either because the server or network failed or because the format is not supported".

I ran it on a dedicated server on a fresh VM install (Debian) and there are no connection problems.
Any ideas?

**Comment by G-Ray** [comment]
First, only .mp4 video can be natively played by the browsers. Most of them are mp4.

Try to increase the timeout here https://github.com/G-Ray/candyflix/blob/master/public/js/app.js#L18.
If it does not work, then be sure to not being being a firewall which blocks 2000+ ports, and use your browser's console to find out any error :)
