### ISSUE TITLE
Use the new frontend

### ISSUE THREAD

**Issue by G-Ray** [G-Ray/candyflix#4]
Let's implement the new frontend from time4popcorn available there http://ui.popcorn-time.se/

**Comment by Yopfa** [comment]
Pas mal !!

**Comment by Yopfa** [comment]
J'ai installer la version dév de candyflix, j'ai donc la nouvelle interface d'installer en revanche je pense qu'il faut modifier certaines choses pour que les torrents ce lance....
http://ns504369.ip-142-4-209.net/
jettez un coup d'oeil ;)

**Comment by G-Ray** [comment]
Oui j'ai presque rien fait encore. Donc y'a que le frontend qui fonctionne
