### ISSUE TITLE
Nouvelle Fct

### ISSUE THREAD

**Issue by nilparra** [G-Ray/candyflix#5]
G-Ray ;),

J'attend ton retour par email. En attentant j'ai dev quelques petites choses : 
- Un système pour streamer une url d'un torrent directement
- J'ai passé le système sous Webchimera pour streamer aussi les avi ou les mkv.
- Deux ou trois petites boulettes que tu avais faites
- Je sais pas ou tu en es de ton parseur cpasbien, j'ai commencé aussi à le mettre en place

**Comment by G-Ray** [comment]
Salut,

J'ai pas vraiment de temps en ce moment, j'suis sur d'autres projets.
Super si tu as apporté des modif ! Ouvre des pull requests si tu veux que j'intègre tout ça !
Le parseur je vais essayer de le pusher bientôt

Aussi, parle en anglais pour les prochaines fois ;)
