### ISSUE TITLE
proxy_pass apache2

### ISSUE THREAD

**Issue by hostile123** [G-Ray/candyflix#9]
Hi how to set it under apache2 on ubuntu

Cuz when i go to site port 3000 its blank page

Where to set proxy_pass in apache2 

Thx

**Comment by Pafzedog** [comment]
you have to serve the frontend folder on default port with apache (not port 3000) and set a proxypass in this configuration as http://your.own.server/socket.io url match this local address : http://localhost:3000

You can read a little ;)
https://httpd.apache.org/docs/2.2/mod/mod_proxy.html#proxypass
